apiVersion: v1
kind: Service
metadata:
  labels:
    name: autocomplete
  name: autocomplete
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: autocomplete
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autocomplete
spec:
  selector:
    matchLabels:
      app: autocomplete
  template:
    metadata:
      labels:
        app: autocomplete
    spec:
      containers:
      - name: autocomplete
        image: mattsday/autocomplete:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: autocomplete-map
  name: autocomplete-map
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: autocomplete-map
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autocomplete-map
spec:
  selector:
    matchLabels:
      app: autocomplete-map
  template:
    metadata:
      labels:
        app: autocomplete-map
    spec:
      containers:
      - name: autocomplete-map
        image: mattsday/autocomplete-map:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: presentation
  name: presentation
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: presentation
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presentation
spec:
  selector:
    matchLabels:
      app: presentation
  template:
    metadata:
      labels:
        app: presentation
    spec:
      containers:
      - name: presentation
        image: mattsday/presentation:latest
        ports:
        - containerPort: 8080

